[project]
name = "k-stt-typer"
version = "0.1.0"
description = "One hotkey speech-to-text tool for Mac using local Whisper.cpp"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.0",
    "pyaudio>=0.2.11",
    "pyperclip>=1.9.0",
    "pynput>=1.8.1",
]
